exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = ! monarch-toggle-enabled waybar-off && uwsm-app -- waybar
exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- swaybg -i ~/.config/monarch/current/background -m fill
exec-once = uwsm-app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = monarch-first-run
exec-once = monarch-powerprofiles-init
exec-once = uwsm-app -- monarch-hyprland-monitor-watch
