mise settings set upgrade.auto_prune false

work_config="$HOME/Work/.mise.toml"
if [[ -f $work_config && ! -L $work_config ]] &&
  cmp -s "$work_config" <(printf '%s\n' '[env]' '_.path = "{{ cwd }}/bin"'); then
  rm -f -- "$work_config"
elif [[ -f $work_config && ! -L $work_config ]]; then
  python3 "${BASH_SOURCE[0]%/*}/mise-work-path.py" "$work_config"
fi

opencode_versions=$(mise ls --global --json opencode) || return 1
if jq -e 'any(.[]; .installed == true)' <<<"$opencode_versions" >/dev/null &&
  monarch-pkg-missing opencode; then
  echo "Install the Arch opencode package before retiring its mise version." >&2
  return 1
fi
if jq -e 'length > 0' <<<"$opencode_versions" >/dev/null; then
  # Running sessions may still need files from their mise installation.
  mise unuse -g --no-prune opencode || return 1
fi

opencode_wrapper="$HOME/.local/bin/opencode"
if [[ -f $opencode_wrapper && ! -L $opencode_wrapper ]] &&
  [[ $(sed -n '2p' "$opencode_wrapper") == '# Generated by monarch-mise-install.' ]]; then
  rm -f "$opencode_wrapper"
fi
