run_logged $MONARCH_INSTALL/packaging/base.sh
run_logged $MONARCH_INSTALL/packaging/nvim.sh
run_logged $MONARCH_INSTALL/packaging/icons.sh
run_logged $MONARCH_INSTALL/packaging/webapps.sh
run_logged $MONARCH_INSTALL/packaging/mise.sh
run_logged $MONARCH_INSTALL/packaging/tuis.sh
run_logged $MONARCH_INSTALL/packaging/python.sh
run_logged $MONARCH_INSTALL/packaging/asus-rog.sh
run_logged $MONARCH_INSTALL/packaging/framework16.sh
run_logged $MONARCH_INSTALL/packaging/dell-xps-touchpad-haptics.sh
run_logged $MONARCH_INSTALL/packaging/surface.sh
