monarch-webapp-install "ChatGPT" https://chatgpt.com/ ChatGPT.png
monarch-webapp-install "Lumo" https://lumo.proton.me/ Lumo.png
monarch-webapp-install "YouTube" https://youtube.com/ YouTube.png
monarch-webapp-install "Discord" https://discord.com/channels/@me Discord.png
monarch-webapp-install "Teams" https://teams.microsoft.com/ Teams.png
monarch-webapp-install "Outlook" https://outlook.office.com Outlook.png
monarch-webapp-install "Cyberchef" https://gchq.github.io/CyberChef/ Cyberchef.png
monarch-webapp-install "WhatsApp" https://web.whatsapp.com/ WhatsApp.png
monarch-webapp-install "SploitUS" https://sploitus.com/ Sploitus.png