# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(monarch-cmd-terminal-cwd)"
bindd = CTRL ALT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = CTRL ALT, E, Exegol, exec, monarch-menu-exegol
bindd = CTRL ALT, S, SSH Manager, exec, monarch-launch-floating-terminal-with-presentation sshm
bindd = CTRL ALT, W, Browser, exec, monarch-launch-browser
bindd = ALT SHIFT, W, Browser (private), exec, monarch-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, monarch-launch-or-focus deezer-desktop
bindd = SUPER SHIFT, N, Editor, exec, monarch-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, monarch-launch-tui lazydocker

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, E, Email, exec, monarch-launch-or-focus-webapp Outlook "https://outlook.office.com"
bindd = SUPER SHIFT, C, Cyberchef, exec, monarch-launch-webapp Cyberchef "https://gchq.github.io/CyberChef/"
bindd = SUPER SHIFT, T, Teams, exec, monarch-launch-or-focus-webapp Teams "https://teams.microsoft.com/"
bindd = SUPER SHIFT, Y, YouTube, exec, monarch-launch-or-focus-webapp YouTube "https://youtube.com/"

# Overwrite existing bindings, like putting Monarch Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Monarch menu, exec, monarch-menu

binds {
    workspace_back_and_forth = true
}
