$activeBorderColor = rgba(7e33ffee) rgba(b471deee) 45deg
$activeBarBoderColor = rgba(3c2a6cee)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor

    groupbar {
        col.active = $activeBarBoderColor
      }
}
