// Niri theme colours — generated by monarch-theme-set-templates from the
// current theme's colors.toml. Merged into the main layout block by Niri.

layout {
    focus-ring {
        active-color "{{ accent }}"
        inactive-color "{{ color0 }}"
    }

    border {
        active-color "{{ accent }}"
        inactive-color "{{ color0 }}"
    }
}
