# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map ctrl+shift+o launch --location=hsplit --cwd=current
map ctrl+shift+e launch --location=vsplit --cwd=current
map ctrl+shift+t new_tab_with_cwd
map alt+left neighboring_window left
map alt+up neighboring_window up
map alt+right neighboring_window right
map alt+down neighboring_window down
map ctrl+shift+enter toggle_layout stack

# History size
scrollback_pager_history_size 8
touch_scroll_multiplier 4.0

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
enabled_layouts splits, stack
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Cursor trail
cursor_shape beam
cursor_trail 3
cursor_trail_decay 0.1 0.4
