# Signing keys imported and locally signed during install.
# Format: <key id> <keyserver>

# CachyOS
F3B607488DB35A47 keyserver.ubuntu.com

# Monarch
519BC3D5AEA652C94F89F0AAC13B3766D969CE82 keys.openpgp.org
