set -euo pipefail

is_legacy_agent_wrapper() {
  local name="$1"
  local file="$HOME/.local/bin/$name"
  local checksum

  [[ -f $file && ! -L $file ]] || return 1
  checksum=$(sha256sum "$file")
  checksum=${checksum%% *}

  # These are exact outputs from every npx wrapper generator shipped on the
  # supported V4 lineage; a modified file belongs to the user.
  case "$name:$checksum" in
  codex:83e2049bd3aceb9315baef891113084cd58da90f79f245c2905bfb9b473f85a9 | \
    codex:aa0e447be861b173f03ea5cdf4d74c0cb266f078937a9667caf2f10baa1489ac | \
    codex:284bad8b2bd46123defad1fd3d4b4d3f6aec70b74369add52fd2707a38f02113)
    return 0
    ;;
  gemini:12cf78e12f1741b48b2be025801e74bdf009310025cbb8d0916c73be47382f12 | \
    gemini:efadd401e4d3ad26c8e8619ee3bd3e783691f3edc3bf562fd89bdcd3cc29f1bc | \
    gemini:a7ef601d57c20315c297127638bb2a5d7946ea1c7e599f487428e385fcb6776b)
    return 0
    ;;
  copilot:7b056fa754f1481476be29a00555c0a46a2fc7628ac4d66a51d08a727fb9c14d | \
    copilot:dbe263ab39a5dd802c8fb00c932d25edc0b03a28ef73a1af58cfa6d6e3d54d92 | \
    copilot:a03be1e0c7f11439f2223e50680e3463a5148eb9ea210eb0842b6d2d000e63a6)
    return 0
    ;;
  opencode:64242a7b1f18c80449b1dedf1f9014456e6ba948880555797bcb6fd039213f32 | \
    opencode:5a8ce75fd238f95d5e2cc85d5b47b2da79894dfac6e268e592ed8038f13aa05d | \
    opencode:44623bd0a45e49f448ec1006feacc7dedcc74b5f85e7fa9fd1def5aff87c11a5)
    return 0
    ;;
  playwright-cli:a6f3a1a44bcaae6c6dffaf8d667db8c7d52219154b19d897e915d1f39da8b4f3 | \
    playwright-cli:7429554aadd460e6db7d50c2da12c01c7cac01f5b9ed3d478c370ac60c44254e | \
    playwright-cli:1b0768506b5921289a844b68ddbe515527a6ab0682c76868de0467ae202a4b3d)
    return 0
    ;;
  pi:3a575d8912a71afdc8ee6083db2025f2a5e7a11654a9257f4adfc8f36b425548 | \
    pi:9aded70a3b69a309669133ff12723d327a9ec49d51ea15abe5dffe0c9dbe5267 | \
    pi:6be1d2199d82979aa67278fe5513f2b0f485a727acf5ac14bc1ef23355268024 | \
    pi:60c302de0b45e4343afe253666532ba765f17840183dcd822402870b95cdb42b)
    return 0
    ;;
  ghui:ea1ec68d3c2c71db266f3d3f97df2d79ee763d6540175f46fb54a320c582abb4 | \
    crush:b6e9246618be552c8841d7ab3aed18438abb9870dfd521d375a236ccd8358bce | \
    grok:5578cdc2da3149e93ad2bd507af2ea987098316f642b20a63029b65deee99b28)
    return 0
    ;;
  esac

  return 1
}

mkdir -p "$HOME/.local/bin"
transition_tmp=""
legacy_gemini=false

cleanup_agent_transition() {
  local status=$?

  trap - EXIT
  set +e
  [[ -z $transition_tmp ]] || rm -f "$transition_tmp"
  exit "$status"
}

mark_legacy_agent_wrapper() {
  local name="$1"
  local file="$HOME/.local/bin/$name"

  transition_tmp=$(mktemp "$HOME/.local/bin/.$name.XXXXXX")
  sed '1a# Generated by monarch-mise-install.' "$file" >"$transition_tmp"
  chmod --reference="$file" "$transition_tmp"
  mv "$transition_tmp" "$file"
  transition_tmp=""
}

trap cleanup_agent_transition EXIT

for legacy_wrapper in codex gemini copilot opencode playwright-cli pi ghui crush grok; do
  if is_legacy_agent_wrapper "$legacy_wrapper"; then
    if [[ $legacy_wrapper == "gemini" ]]; then
      legacy_gemini=true
    else
      mark_legacy_agent_wrapper "$legacy_wrapper"
    fi
  fi
done

source "$MONARCH_PATH/install/user/mise.sh"

agent_file="$HOME/.config/monarch/defaults/agent"
if [[ -f $agent_file && ! -L $agent_file ]]; then
  default_agent=$(<"$agent_file")
  if [[ $default_agent == "gemini" || $default_agent == "gemini-cli" ]]; then
    transition_tmp=$(mktemp "$agent_file.XXXXXX")
    printf '%s\n' agy >"$transition_tmp"
    chmod --reference="$agent_file" "$transition_tmp"
    mv "$transition_tmp" "$agent_file"
    transition_tmp=""
  fi
fi

if [[ $legacy_gemini == "true" ]]; then
  rm -f "$HOME/.local/bin/gemini"
fi

trap - EXIT
