# Copy / Paste
bindd = SUPER CTRL, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = SUPER CTRL, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X,
bindd = SUPER SHIFT, V, Clipboard manager, exec, monarch-launch-walker -m clipboard