# Grouping / Stacking

group {
  # https://wiki.hypr.land/Configuring/Variables/#groupbar
  auto_group = true             # new windows join the focused unlocked group
  groupbar {
    #  https://wiki.hypr.land/Configuring/Variables/#groupbar
    height = 15
    font_size = 12
    font_weight_active = bold
    gradients = true
  }
}

# Key bindings for Stacking / Grouping windows
# Base combination for this is CONTROL + ALT

# Start/stop a group for the focused window (creates a tabbed stack)
bindd = SUPER ALT, RETURN, start grouping, togglegroup

# Unstack
bindd = SUPER ALT, U, Unstack focused window, moveoutofgroup

# Lock the group
bindd = SUPER ALT,       L, Lock the active group, lockactivegroup, toggle
bindd = SUPER ALT SHIFT, L, Lock all groups,       lockgroups, toogle

# Add the focused window into a neighboring group's stack
bindd = SUPER ALT, LEFT , Stack into left group,  movewindoworgroup, l
bindd = SUPER ALT, RIGHT, Stack into right group, movewindoworgroup, r
bindd = SUPER ALT, UP   , Stack into up group,    movewindoworgroup, u
bindd = SUPER ALT, DOWN , Stack into down group,  movewindoworgroup, d

# Cycle tabs inside the stack, or use the index
bindd = SUPER ALT      , Page_Up   , Next tab in group,     changegroupactive, b
bindd = SUPER ALT      , Page_Down , Prev tab in group,     changegroupactive, f
bindd = SUPER ALT      , code:10   , 1st in group,          changegroupactive, 1
bindd = SUPER ALT      , code:11   , 2nd in group,          changegroupactive, 2
bindd = SUPER ALT      , code:12   , 3rd in group,          changegroupactive, 3
bindd = SUPER ALT      , code:13   , 4th in group,          changegroupactive, 4
bindd = SUPER ALT      , code:14   , 5th in group,          changegroupactive, 5
bindd = SUPER ALT      , code:15   , 6th in group,          changegroupactive, 6
bindd = SUPER ALT      , code:16   , 7th in group,          changegroupactive, 7
bindd = SUPER ALT      , code:17   , 8th in group,          changegroupactive, 8
bindd = SUPER ALT      , code:18   , 9th in group,          changegroupactive, 9
bindd = SUPER ALT      , code:19   , 10th in group,         changegroupactive, 10

# Reorder within the stack
bindd = SUPER ALT CTRL, LEFT , Swap tab forward,  movegroupwindow, b
bindd = SUPER ALT CTRL, RIGHT, Swap tab backward, movegroupwindow
