# Menus
bindd = SUPER, SPACE, Launch apps, exec, monarch-launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, monarch-launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, monarch-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, monarch-menu toggle
bindd = SUPER ALT, SPACE, Monarch menu, exec, monarch-menu
bindd = SUPER SHIFT, L, Power menu, exec, monarch-menu system
bindld = , XF86PowerOff, Power menu, exec, monarch-menu system
bindd = SUPER, K, Show key bindings, exec, monarch-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aestheticsund
bindd = SUPER CTRL, SPACE, Theme background menu, exec, monarch-menu background
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, monarch-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, monarch-hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, monarch-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, monarch-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Lock screen
bindd = SUPER, L, Lock screen, exec, monarch-lock-screen

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, monarch-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, monarch-toggle-nightlight

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, monarch-brightness-display-apple -5000
bindd = CTRL, F2, Apple Display brightness up, exec, monarch-brightness-display-apple +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, monarch-brightness-display-apple +60000

# Screenshots
bindd = , PRINT, Screenshot with editing, exec, monarch-cmd-screenshot
bindd = SUPER SHIFT, S, Screenshot to clipboard, exec, monarch-cmd-screenshot smart clipboard
bindd = ALT, PRINT, Screenrecording, exec, monarch-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a


# File sharing
bindd = SUPER CTRL, S, Share, exec, monarch-menu share

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send "󰁹    Battery is at $(monarch-battery-remaining)%"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, monarch-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, monarch-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, monarch-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, monarch-launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1
