# Menus
bindd = SUPER, SPACE, Launch apps, exec, monarch-launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, monarch-launch-walker -m symbols
bindd = SUPER ALT, SPACE, Monarch menu, exec, monarch-menu
bindd = SUPER SHIFT, L, Power menu, exec, monarch-menu system
bindld = , XF86PowerOff, Power menu, exec, monarch-menu system
bindd = SUPER, K, Show key bindings, exec, monarch-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER CTRL, SPACE, Next background in theme, exec, monarch-theme-bg-next
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, monarch-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications" && pkill -RTMIN+9 waybar
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke

# Lock screen
bindd = SUPER, L, Lock screen, exec, monarch-lock-screen

# Toggle idling
bindd = SUPER CTRL, I, Toggle locking on idle, exec, monarch-toggle-idle

# Toggle nightlight
bindd = SUPER CTRL, N, Toggle nightlight, exec, monarch-toggle-nightlight

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, monarch-cmd-apple-display-brightness -5000
bindd = CTRL, F2, Apple Display brightness up, exec, monarch-cmd-apple-display-brightness +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, monarch-cmd-apple-display-brightness +60000

# Screenshots
bindd = , PRINT, Screenshot with editing, exec, monarch-cmd-screenshot
bindd = SHIFT, PRINT, Screenshot to clipboard, exec, monarch-cmd-screenshot smart clipboard
bindd = SUPER SHIFT, S, Screenshot to clipboard, exec, monarch-cmd-screenshot smart clipboard
bindd = ALT, PRINT, Screenrecording, exec, monarch-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a


# File sharing
bindd = SUPER CTRL, S, Share, exec, monarch-menu share

# Waybar-less information
bindd = SUPER CTRL, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"
bindd = SUPER CTRL, B, Show battery remaining, exec, notify-send "󰁹    Battery is at $(monarch-battery-remaining)%"